/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
package parser;
import java.util.ArrayList;
import syntax.*;
import main.CompileError;

public class MiniJavaParser implements MiniJavaParserConstants {

// Program expansions
  static final public Program JProgram() throws ParseException {
  MainClass m; ArrayList<ClassDecl> cl = new ArrayList<ClassDecl>();
    try {
      m = JMainClass();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        cl = JClassDeclList();
        break;
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      jj_consume_token(0);
                  {if (true) return new Program(m, cl);}
    } catch (ParseException e) {
                syntax_error(e);
                {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  static final public MainClass JMainClass() throws ParseException {
  Identifier cn; Identifier arg; Statement s;
    jj_consume_token(CLASS);
    cn = JIdentifier();
    jj_consume_token(LBRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(LPAREN);
    jj_consume_token(STRING);
    jj_consume_token(LBRACKET);
    jj_consume_token(RBRACKET);
    arg = JIdentifier();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    s = JStatement();
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
          {if (true) return new MainClass(cn, arg, s);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<ClassDecl> JClassDeclList() throws ParseException {
  ClassDecl cd; ArrayList<ClassDecl> cl = new ArrayList<ClassDecl>();
    cd = JClassDecl();
                            cl = new ArrayList<ClassDecl>(); cl.add(cd);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      cd = JClassDecl();
                              cl.add(cd);
    }
          {if (true) return cl;}
    throw new Error("Missing return statement in function");
  }

  static final public ClassDecl JClassDecl() throws ParseException {
  ClassDecl cd;
    if (jj_2_1(3)) {
      cd = JExtendedClassDecl();
          {if (true) return cd;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        cd = JRootClassDecl();
          {if (true) return cd;}
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public SimpleClassDecl JRootClassDecl() throws ParseException {
  Identifier cn; ArrayList<VarDecl> vl = new ArrayList<VarDecl>(); ArrayList<MethodDecl> ml = new ArrayList<MethodDecl>();
    jj_consume_token(CLASS);
    cn = JIdentifier();
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOLEAN:
    case IDENTIFIER:
      vl = JVarDeclList();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUBLIC:
      ml = JMethodDeclList();
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
          {if (true) return new SimpleClassDecl(cn, vl, ml);}
    throw new Error("Missing return statement in function");
  }

  static final public ExtendingClassDecl JExtendedClassDecl() throws ParseException {
  Identifier cn; Identifier scn; ArrayList<VarDecl> vl = new ArrayList<VarDecl>(); ArrayList<MethodDecl> ml = new ArrayList<MethodDecl>();
    jj_consume_token(CLASS);
    cn = JIdentifier();
    jj_consume_token(EXTENDS);
    scn = JIdentifier();
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOLEAN:
    case IDENTIFIER:
      vl = JVarDeclList();
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUBLIC:
      ml = JMethodDeclList();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
          {if (true) return new ExtendingClassDecl(cn, scn, vl, ml);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<VarDecl> JVarDeclList() throws ParseException {
  VarDecl vd; ArrayList<VarDecl> vl = new ArrayList<VarDecl>();
    vd = JVarDecl();
                          vl = new ArrayList<VarDecl>(); vl.add(vd);
    label_2:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_2;
      }
      vd = JVarDecl();
                                         vl.add(vd);
    }
          {if (true) return vl;}
    throw new Error("Missing return statement in function");
  }

  static final public VarDecl JVarDecl() throws ParseException {
  Type t; Identifier i;
    t = JType();
    i = JIdentifier();
    jj_consume_token(SEMICOLON);
          {if (true) return new VarDecl(t, i);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<MethodDecl> JMethodDeclList() throws ParseException {
  MethodDecl md; ArrayList<MethodDecl> ml = new ArrayList<MethodDecl>();
    md = JMethodDecl();
                             ml = new ArrayList<MethodDecl>(); ml.add(md);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      md = JMethodDecl();
                               ml.add(md);
    }
          {if (true) return ml;}
    throw new Error("Missing return statement in function");
  }

// Method declaration expansions
  static final public MethodDecl JMethodDecl() throws ParseException {
        Type t;
        Identifier i;
        Expression e;
        ArrayList<Formal> fl = new ArrayList<Formal>();
        ArrayList<VarDecl> vl = new ArrayList<VarDecl>();
        ArrayList<Statement> sl = new ArrayList<Statement>();
    jj_consume_token(PUBLIC);
    t = JType();
    i = JIdentifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOLEAN:
    case IDENTIFIER:
      fl = JParamDeclList();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    if (jj_2_3(2147483647)) {
      vl = JVarDeclList();
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case PRINTLN:
    case LBRACE:
    case IDENTIFIER:
      sl = JStatementList();
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(RETURN);
    e = JExpression();
    jj_consume_token(SEMICOLON);
    jj_consume_token(RBRACE);
          {if (true) return new MethodDecl(t, i, fl, vl, sl, e);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Formal> JParamDeclList() throws ParseException {
  Formal f; ArrayList<Formal> fl = new ArrayList<Formal>();
    f = JParamDecl();
                           fl = new ArrayList<Formal>(); fl.add(f);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      f = JParamDeclListTail();
                                     fl.add(f);
    }
          {if (true) return fl;}
    throw new Error("Missing return statement in function");
  }

  static final public Formal JParamDeclListTail() throws ParseException {
  Formal f;
    jj_consume_token(COMMA);
    f = JParamDecl();
          {if (true) return f;}
    throw new Error("Missing return statement in function");
  }

  static final public Formal JParamDecl() throws ParseException {
  Type t; Identifier i;
    t = JType();
    i = JIdentifier();
          {if (true) return new Formal( t, i);}
    throw new Error("Missing return statement in function");
  }

  static final public Type JType() throws ParseException {
  Token t;
    if (jj_2_4(3)) {
      jj_consume_token(INT);
      jj_consume_token(LBRACKET);
      jj_consume_token(RBRACKET);
                                     {if (true) return Type.THE_INT_ARRAY_TYPE;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOLEAN:
        jj_consume_token(BOOLEAN);
                      {if (true) return Type.THE_BOOLEAN_TYPE;}
        break;
      case INT:
        jj_consume_token(INT);
                  {if (true) return new IntegerType();}
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
                             {if (true) return new IdentifierType(t.beginLine, t.beginColumn, t.image);}
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Statement> JStatementList() throws ParseException {
  Statement s; ArrayList<Statement> sl = new ArrayList<Statement>();
    s = JStatement();
                           sl = new ArrayList<Statement>(); sl.add(s);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case PRINTLN:
      case LBRACE:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      s = JStatement();
                             sl.add(s);
    }
          {if (true) return sl;}
    throw new Error("Missing return statement in function");
  }

// Statement expansions
  static final public Statement JStatement() throws ParseException {
  Statement s;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACE:
        s = JBlock();
                               {if (true) return s;}
        break;
      case IF:
        s = JIfStatement();
                                       {if (true) return s;}
        break;
      case WHILE:
        s = JWhileStatement();
                                          {if (true) return s;}
        break;
      case PRINTLN:
        s = JPrintCall();
                                     {if (true) return s;}
        break;
      default:
        jj_la1[13] = jj_gen;
        if (jj_2_5(2)) {
          s = JAssignment();
                                                   {if (true) return s;}
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            s = JArrayAssignment();
                                           {if (true) return s;}
            break;
          default:
            jj_la1[14] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    } catch (ParseException e) {
                syntax_error(e);
                skip_to_expected(e.expectedTokenSequences);
                {if (true) return new Block(new ArrayList<Statement>());}
    }
    throw new Error("Missing return statement in function");
  }

  static final public Block JBlock() throws ParseException {
  ArrayList<Statement> sl = new ArrayList<Statement>();
    try {
      jj_consume_token(LBRACE);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case PRINTLN:
      case LBRACE:
      case IDENTIFIER:
        sl = JStatementList();
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      jj_consume_token(RBRACE);
                  {if (true) return new Block(sl);}
    } catch (ParseException e) {
                syntax_error(e);
                skip_to_expected(e.expectedTokenSequences);
                {if (true) return new Block(new ArrayList<Statement>());}
    }
    throw new Error("Missing return statement in function");
  }

  static final public If JIfStatement() throws ParseException {
  Token t; Expression e; Statement s1; Statement s2;
    /*
    	LOOKAHEAD(IfElseStatement()) IfElseStatement()
    	| IfThenStatement()	
    }
    
    void IfThenStatement():
    {}
    {
    	"if" "(" Expression() ")" Statement()
    }
    
    void IfElseStatement():
    {}
    {*/
            t = jj_consume_token(IF);
    jj_consume_token(LPAREN);
    e = JExpression();
    jj_consume_token(RPAREN);
    s1 = JStatement();
    jj_consume_token(ELSE);
    s2 = JStatement();
          {if (true) return new If(t.beginLine, t.beginColumn, e, s1, s2);}
    throw new Error("Missing return statement in function");
  }

  static final public While JWhileStatement() throws ParseException {
  Token t; Expression e; Statement s;
    t = jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    e = JExpression();
    jj_consume_token(RPAREN);
    s = JStatement();
          {if (true) return new While(t.beginLine, t.beginColumn, e, s);}
    throw new Error("Missing return statement in function");
  }

  static final public Print JPrintCall() throws ParseException {
  Token t; Expression e;
    t = jj_consume_token(PRINTLN);
    jj_consume_token(LPAREN);
    e = JExpression();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
          {if (true) return new Print(t.beginLine, t.beginColumn, e);}
    throw new Error("Missing return statement in function");
  }

  static final public Assign JAssignment() throws ParseException {
  Token t; Identifier i; Expression e;
    i = JIdentifier();
    t = jj_consume_token(GETS);
    e = JExpression();
    jj_consume_token(SEMICOLON);
          {if (true) return new Assign(t.beginLine, t.beginColumn, i, e);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayAssign JArrayAssignment() throws ParseException {
  Token t; Identifier i; Expression ie; Expression ae;
    i = JIdentifier();
    jj_consume_token(LBRACKET);
    ie = JExpression();
    jj_consume_token(RBRACKET);
    t = jj_consume_token(GETS);
    ae = JExpression();
    jj_consume_token(SEMICOLON);
          {if (true) return new ArrayAssign(t.beginLine, t.beginColumn, i, ie, ae);}
    throw new Error("Missing return statement in function");
  }

// Expression expansions
  static final public Expression JExpression() throws ParseException {
  Expression e;
    if (jj_2_6(2147483647)) {
      e = JAndExpr();
                                                          {if (true) return e;}
    } else if (jj_2_7(2147483647)) {
      e = JCompareExpr();
                                                               {if (true) return e;}
    } else if (jj_2_8(2147483647)) {
      e = JPlusExpr();
                                                            {if (true) return e;}
    } else if (jj_2_9(2147483647)) {
      e = JMinusExpr();
                                                             {if (true) return e;}
    } else if (jj_2_10(2147483647)) {
      e = JMultExpr();
                                                            {if (true) return e;}
    } else if (jj_2_11(2147483647)) {
      e = JArrayLookupExpr();
                                                                   {if (true) return e;}
    } else if (jj_2_12(2147483647)) {
      e = JLengthExpr();
                                                                       {if (true) return e;}
    } else if (jj_2_13(2147483647)) {
      e = JFunctionCall();
                                                                                   {if (true) return e;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TRUE:
      case FALSE:
      case THIS:
      case NEW:
      case NOT:
      case LPAREN:
      case IDENTIFIER:
      case INTEGER_LITERAL:
        e = JSubExpression();
                                 {if (true) return e;}
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public And JAndExpr() throws ParseException {
  Token t; Expression e1; Expression e2;
    e1 = JSubExpression();
    t = jj_consume_token(AND);
    e2 = JSubExpression();
          {if (true) return new And(t.beginLine, t.beginColumn, e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public LessThan JCompareExpr() throws ParseException {
  Token t; Expression e1; Expression e2;
    e1 = JSubExpression();
    t = jj_consume_token(LESSTHAN);
    e2 = JSubExpression();
          {if (true) return new LessThan(t.beginLine, t.beginColumn, e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Plus JPlusExpr() throws ParseException {
  Token t; Expression e1; Expression e2;
    e1 = JSubExpression();
    t = jj_consume_token(PLUS);
    e2 = JSubExpression();
          {if (true) return new Plus(t.beginLine, t.beginColumn, e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Minus JMinusExpr() throws ParseException {
  Token t; Expression e1; Expression e2;
    e1 = JSubExpression();
    t = jj_consume_token(MINUS);
    e2 = JSubExpression();
          {if (true) return new Minus(t.beginLine, t.beginColumn, e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Times JMultExpr() throws ParseException {
  Token t; Expression e1; Expression e2;
    e1 = JSubExpression();
    t = jj_consume_token(MULT);
    e2 = JSubExpression();
          {if (true) return new Times(t.beginLine, t.beginColumn, e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayLookup JArrayLookupExpr() throws ParseException {
  Token t; Expression e; Expression ie;
    e = JSubExpression();
    t = jj_consume_token(LBRACKET);
    ie = JSubExpression();
    jj_consume_token(RBRACKET);
          {if (true) return new ArrayLookup(t.beginLine, t.beginColumn, e, ie);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayLength JLengthExpr() throws ParseException {
  Token t; Expression e;
    e = JSubExpression();
    t = jj_consume_token(DOT);
    jj_consume_token(LENGTH);
          {if (true) return new ArrayLength(t.beginLine, t.beginColumn, e);}
    throw new Error("Missing return statement in function");
  }

  static final public Call JFunctionCall() throws ParseException {
  Token t; Expression e; Identifier i; ArrayList<Expression> el = new ArrayList<Expression>();
    // Does this use the identifier type class? Probably not.
            e = JSubExpression();
    jj_consume_token(DOT);
    i = JIdentifier();
    t = jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case THIS:
    case NEW:
    case NOT:
    case LPAREN:
    case IDENTIFIER:
    case INTEGER_LITERAL:
      el = JMethodParams();
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
          {if (true) return new Call(t.beginLine, t.beginColumn, e, i, el);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Expression> JMethodParams() throws ParseException {
  Expression e; ArrayList<Expression> el = new ArrayList<Expression>();
    e = JExpression();
                            el = new ArrayList<Expression>(); el.add(e);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_6;
      }
      e = JMethodParamsTail();
                                    el.add(e);
    }
          {if (true) return el;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression JMethodParamsTail() throws ParseException {
  Expression e;
    jj_consume_token(COMMA);
    e = JExpression();
                                {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression JSubExpression() throws ParseException {
  Token t; Identifier i; IdentifierExp ie; Expression e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      t = jj_consume_token(INTEGER_LITERAL);
          {if (true) return new IntegerLiteral(t.beginLine, t.beginColumn, Integer.parseInt(t.image));}
      break;
    case TRUE:
      t = jj_consume_token(TRUE);
                       {if (true) return new True(t.beginLine, t.beginColumn);}
      break;
    case FALSE:
      t = jj_consume_token(FALSE);
                        {if (true) return new False(t.beginLine, t.beginColumn);}
      break;
    case THIS:
      t = jj_consume_token(THIS);
                       {if (true) return new This(t.beginLine, t.beginColumn);}
      break;
    default:
      jj_la1[19] = jj_gen;
      if (jj_2_14(2)) {
        e = JNewArray();
                                         {if (true) return e;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NEW:
          t = jj_consume_token(NEW);
          i = JIdentifier();
          jj_consume_token(LPAREN);
          jj_consume_token(RPAREN);
                                                {if (true) return new NewObject(t.beginLine, t.beginColumn, i);}
          break;
        case NOT:
          t = jj_consume_token(NOT);
          e = JExpression();
                                        {if (true) return new Not(t.beginLine, t.beginColumn, e);}
          break;
        case LPAREN:
          jj_consume_token(LPAREN);
          e = JExpression();
          jj_consume_token(RPAREN);
                                      {if (true) return e;}
          break;
        case IDENTIFIER:
          ie = JIdentifierExp();
                                  {if (true) return ie;}
          break;
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public IdentifierExp JIdentifierExp() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
          {if (true) return new IdentifierExp(t.beginLine, t.beginColumn, t.image);}
    throw new Error("Missing return statement in function");
  }

  static final public Identifier JIdentifier() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
          {if (true) return new Identifier(t.beginLine, t.beginColumn, t.image);}
    throw new Error("Missing return statement in function");
  }

  static final public NewArray JNewArray() throws ParseException {
  Token t; Expression e;
    t = jj_consume_token(NEW);
    jj_consume_token(INT);
    jj_consume_token(LBRACKET);
    e = JExpression();
    jj_consume_token(RBRACKET);
          {if (true) return new NewArray(t.beginLine, t.beginColumn, e);}
    throw new Error("Missing return statement in function");
  }

  static void syntax_error(ParseException e) throws ParseException {
        Token t = e.currentToken.next;
        int exp = -1;

        for(int i = 0; exp == -1 && i < e.expectedTokenSequences.length; i++)
                for(int j = 0; exp == -1 && j < e.expectedTokenSequences[i].length; j++)
                        exp = e.expectedTokenSequences[i][j];
        if (exp != -1)
                CompileError.printError(t.beginLine, t.beginColumn,
                        String.format("Syntax Error: expecting a %s\u005cn", e.tokenImage[exp]));
        else
                CompileError.printError(t.beginLine, t.beginColumn, "Syntax Error: unknown");
  }

  static void skip_to_matching_brace() throws ParseException {
        Token t;
        int depth = 1;
        while (true) {
                t = getToken(1);
                if(t.kind == LBRACE) depth++;
                if(t.kind == RBRACE) {
                        depth--;
                        if(depth == 0) break;
                }
                if(t.kind == EOF) break;
                t = getNextToken();
        }
  }

  static void skip_to_kind(int kind) throws ParseException {
        Token t;
        do {
                t = getNextToken();
        } while (t.kind != kind && t.kind != EOF);
  }

  static void skip_to_expected(int [][] expected) throws ParseException {
        Token t;
        do {
                t = getNextToken();
                for (int i = 0; i < expected.length; i++)
                        if(t.kind == EOF || t.kind == expected[i][0])
                                return;
        } while(true);
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_3R_10() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(GETS)) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_3R_48()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_3R_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_47()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_11()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(MULT)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    if (jj_3R_14()) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_3R_8()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_2()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_7() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(EXTENDS)) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(LESSTHAN)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(LBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(MULT)) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(AND)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(LESSTHAN)) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(AND)) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_3R_44()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_3R_41()) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[21];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x8,0x8,0x8,0x1800,0x10,0x1800,0x10,0x10,0x1800,0x10082002,0x0,0x1800,0x10082002,0x10082002,0x0,0x10082002,0x203c000,0x203c000,0x0,0x1c000,0x2020000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x10,0x0,0x10,0x0,0x0,0x10,0x10,0x8,0x10,0x10,0x0,0x10,0x10,0x31,0x31,0x8,0x20,0x11,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[14];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MiniJavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MiniJavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[48];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 21; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 48; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 14; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

                            }
